# Generated by Django 6.0.3 on 2026-03-23 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
